-- MySQL Script generated by MySQL Workbench
-- Mon May 16 18:31:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Pronuntia_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Pronuntia_db` ;

-- -----------------------------------------------------
-- Schema Pronuntia_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pronuntia_db` DEFAULT CHARACTER SET utf8 ;
USE `Pronuntia_db` ;

-- -----------------------------------------------------
-- Table `Pronuntia_db`.`Utenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pronuntia_db`.`Utenti` ;

CREATE TABLE IF NOT EXISTS `Pronuntia_db`.`Utenti` (
  `idUtente` INT UNSIGNED NOT NULL,
  `email` VARCHAR(55) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idUtente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pronuntia_db`.`Logopedisti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pronuntia_db`.`Logopedisti` ;

CREATE TABLE IF NOT EXISTS `Pronuntia_db`.`Logopedisti` (
  `Utenti_idUtente` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cognome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Utenti_idUtente`),
  CONSTRAINT `fk_Logopedisti_Utenti`
    FOREIGN KEY (`Utenti_idUtente`)
    REFERENCES `Pronuntia_db`.`Utenti` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pronuntia_db`.`Bambini`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pronuntia_db`.`Bambini` ;

CREATE TABLE IF NOT EXISTS `Pronuntia_db`.`Bambini` (
  `Utenti_idUtente` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cognome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Utenti_idUtente`),
  CONSTRAINT `fk_Bambini_Utenti1`
    FOREIGN KEY (`Utenti_idUtente`)
    REFERENCES `Pronuntia_db`.`Utenti` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pronuntia_db`.`caregiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pronuntia_db`.`caregiver` ;

CREATE TABLE IF NOT EXISTS `Pronuntia_db`.`caregiver` (
  `Utenti_idUtente` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cognome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Utenti_idUtente`),
  CONSTRAINT `fk_caregiver_Utenti1`
    FOREIGN KEY (`Utenti_idUtente`)
    REFERENCES `Pronuntia_db`.`Utenti` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pronuntia_db`.`Librerie Esercizi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pronuntia_db`.`Librerie Esercizi` ;

CREATE TABLE IF NOT EXISTS `Pronuntia_db`.`Librerie Esercizi` (
  `idEsercizio` INT UNSIGNED NOT NULL COMMENT 'CONTIENE ESERCIZI SINGOLI',
  `testo per funzionamento` LONGTEXT NOT NULL,
  PRIMARY KEY (`idEsercizio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pronuntia_db`.`Terapia Assegnata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pronuntia_db`.`Terapia Assegnata` ;

CREATE TABLE IF NOT EXISTS `Pronuntia_db`.`Terapia Assegnata` (
  `ID_terapia_assegnata` INT UNSIGNED NOT NULL,
  `data` DATE NOT NULL,
  `batteria di esercizi_ID_serie_esercizi` INT NOT NULL,
  `Bambini_Utenti_idUtente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID_terapia_assegnata`),
  INDEX `fk_Terapia Assegnata_Bambini1_idx` (`Bambini_Utenti_idUtente` ASC) VISIBLE,
  CONSTRAINT `fk_Terapia Assegnata_Bambini1`
    FOREIGN KEY (`Bambini_Utenti_idUtente`)
    REFERENCES `Pronuntia_db`.`Bambini` (`Utenti_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pronuntia_db`.`batteria di esercizi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pronuntia_db`.`batteria di esercizi` ;

CREATE TABLE IF NOT EXISTS `Pronuntia_db`.`batteria di esercizi` (
  `batteria di esercizicol` INT UNSIGNED NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `descrizione` MEDIUMTEXT NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `Logopedisti_Utenti_idUtente` INT UNSIGNED NOT NULL,
  `Librerie Esercizi_idEsercizio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`batteria di esercizicol`),
  INDEX `fk_batteria di esercizi_Logopedisti1_idx` (`Logopedisti_Utenti_idUtente` ASC) VISIBLE,
  INDEX `fk_batteria di esercizi_Librerie Esercizi1_idx` (`Librerie Esercizi_idEsercizio` ASC) VISIBLE,
  CONSTRAINT `fk_batteria di esercizi_Logopedisti1`
    FOREIGN KEY (`Logopedisti_Utenti_idUtente`)
    REFERENCES `Pronuntia_db`.`Logopedisti` (`Utenti_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_batteria di esercizi_Librerie Esercizi1`
    FOREIGN KEY (`Librerie Esercizi_idEsercizio`)
    REFERENCES `Pronuntia_db`.`Librerie Esercizi` (`idEsercizio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pronuntia_db`.`Curato da :`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pronuntia_db`.`Curato da :` ;

CREATE TABLE IF NOT EXISTS `Pronuntia_db`.`Curato da :` (
  `Logopedisti_Utenti_idUtente` INT UNSIGNED NOT NULL,
  `Bambini_Utenti_idUtente` INT UNSIGNED NOT NULL,
  `caregiver_Utenti_idUtente` INT UNSIGNED NOT NULL,
  `Data` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Logopedisti_Utenti_idUtente`, `Bambini_Utenti_idUtente`, `caregiver_Utenti_idUtente`),
  INDEX `fk_Bambini_has_caregiver_caregiver1_idx` (`caregiver_Utenti_idUtente` ASC) VISIBLE,
  INDEX `fk_Bambini_has_caregiver_Bambini1_idx` (`Bambini_Utenti_idUtente` ASC) VISIBLE,
  INDEX `fk_Relazione_Logopedisti1_idx` (`Logopedisti_Utenti_idUtente` ASC) VISIBLE,
  CONSTRAINT `fk_Bambini_has_caregiver_Bambini1`
    FOREIGN KEY (`Bambini_Utenti_idUtente`)
    REFERENCES `Pronuntia_db`.`Bambini` (`Utenti_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bambini_has_caregiver_caregiver1`
    FOREIGN KEY (`caregiver_Utenti_idUtente`)
    REFERENCES `Pronuntia_db`.`caregiver` (`Utenti_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Relazione_Logopedisti1`
    FOREIGN KEY (`Logopedisti_Utenti_idUtente`)
    REFERENCES `Pronuntia_db`.`Logopedisti` (`Utenti_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
